### ISSUE TITLE
Fix binaries for MacOS

### ISSUE THREAD

**Issue by jwoudenberg** [jwoudenberg/elm-pair#11]
The github action setup seems to generate very small binaries that do not work for some reason, and the binary I manually uploaded links to C dependencies in the nix store.

Uncovered in: https://github.com/jwoudenberg/elm-pair/issues/8

**Comment by Janiczek** [comment]
Just a note that release-7 and earlier were non-problematic. The problem started happening sometime around release-8.

**Comment by jwoudenberg** [comment]
No idea why the release script broke between release 7 and 8, and whether it was my code changes that did it, or one of the workflow dependencies or something. Running a simpler `cargo build` command without the `--target` flag seems to help though, MacOS binary is restored!

Commit: https://github.com/jwoudenberg/elm-pair/commit/5f56865819475bba6082ee5ea0b96703572342a9

**Comment by Janiczek** [comment]
Confirming it works for me now via the official channel 🙂 :tada:
