### ISSUE TITLE
Unwanted rename of unrelated lambda argument

### ISSUE THREAD

**Issue by Janiczek** [jwoudenberg/elm-pair#13]
Hello!
Sorry my issue won't be as polished / minified as usual, I'm a bit swamped at the moment.
I just want to quickly hint at one false positive I found:

<img width="1153" alt="Screenshot 2022-03-03 at 14 43 24" src="https://user-images.githubusercontent.com/149425/156576622-c9122521-4fcf-446a-a78e-c5143a8c53d1.png">

Renaming a lambda argument from `_` to `options` in one `case..of` variant caused a rename from `options` to `options2` in a totally unrelated `case..of` variant. That probably shouldn't happen?

**Comment by jwoudenberg** [comment]
Thank you for reporting this, despite being swamped! I understand the problem and am going to take a look tomorrow!

**Comment by jwoudenberg** [comment]
Hey @Janiczek! I just pushed release 11, which includes a fix. Thank you again for a super clear bug report!
