### ISSUE TITLE
elm-pair doesn't ignore buffers that don't correspond to files

### ISSUE THREAD

**Issue by Janiczek** [jwoudenberg/elm-pair#14]
Sorry, I don't know the correct vim terminology.
Anyways, I'm using `fugitive` for my Git Vim needs.
In particular I'm using `dd` to open a three-way diff of a file when solving merge conflicts.

When opening that diff for the first time, it works correctly. **But when I try to open another one, elm-pair throws an error.**

https://user-images.githubusercontent.com/149425/157730829-2801c7f5-d7a4-4b31-a9a3-034d20334df8.mp4

Here's the Vim error:
```
Error detected while processing FileType Autocommands for "elm":
E5108: Error executing lua Vim:E475: Invalid argument: Channel doesn't exist
stack traceback:
        [C]: in function 'rpcnotify'
        /Users/martinjaniczek/.vim/elm-pair/lua/elm-pair.lua:3: in function 'on_elm_buffer'
        /Users/martinjaniczek/.vim/elm-pair/lua/elm-pair.lua:9: in function </Users/martinjaniczek/.vim/elm-pair/lua/elm-pair.lua:6>
E5108: Error executing lua Vim:E475: Invalid argument: Channel doesn't exist
stack traceback:
        [C]: in function 'rpcnotify'
        /Users/martinjaniczek/.vim/elm-pair/lua/elm-pair.lua:3: in function 'on_elm_buffer'
        /Users/martinjaniczek/.vim/elm-pair/lua/elm-pair.lua:9: in function </Users/martinjaniczek/.vim/elm-pair/lua/elm-pair.lua:6>
```

and here's an `elm-pair` log:
```
[info] Found Elm compiler binary: "/Users/martinjaniczek/.vim/elm-pair/lua/../elm"
[info] elm-pair has started
[info] editor neovim connected and given id 0
[info] new buffer opened: Buffer { editor_id: 0, buffer_id: 1 }
[info] new buffer opened: Buffer { editor_id: 0, buffer_id: 3 }
[error] thread for editor 0 failed with error: [src/lib/log.rs:85] failed sending message to channel: SendError { .. }
[error] Can't find Elm project root for path "fugitive:///Users/martinjaniczek/Localhost/gwi/research-ui/.git//2/app/src/Module/ProjectManagement/Project/DataProcessing/Configurations/CreateEdit.elm": [src/elm/project.rs:13] Did not find elm.json file in any ancestor directory of module path
[error] exiting because of: [src/elm/project.rs:13] Did not find elm.json file in any ancestor directory of module path
```

(My elm-pair version is 0.10.0 currently - forgot to upgrade to the last one. I'll do that and confirm whether the issue is still happening after submitting the issue.)

My view is that perhaps elm-pair could/should ignore `fugitive://` paths (or non-`file://` paths perhaps) somehow, but I don't know your internal representation to suggest anything more specific.

**Comment by Janiczek** [comment]
Confirming this still happens on elm-pair 0.11.0

**Comment by jwoudenberg** [comment]
Thank you, that's super clear as usual! I'm on holiday this week and will look into this next week!

**Comment by jwoudenberg** [comment]
Release 12 is on its way and contains a fix for this. Thank you!
