### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by wolfadex** [jwoudenberg/elm-pair#16]
Environment:
- MacBook Pro 16-inch, 2019
- OSX v12.2.1
- 64 GB RAM
- VSCode v1.65.2

Error message:
```
Command failed: /Users/wolfgang/.vscode/extensions/hjgames.elm-pair-0.13.0/elm-pair \bin\sh:
/nix/store/pbfraw351mksnkp2ni9c4rkc9cpp89iv-bash-5.1-p12/bin/bash bad interpreter: No such file or directory
```

I am not using Nix, if that's relevant.

**Comment by jwoudenberg** [comment]
Thank you for reporting this! I'm going to do some digging and get back to you.

**Comment by ryan-haskell** [comment]
🙋  Same issue for me, on this machine:
- MacBook Pro (13-inch, 2020)
- OSX v12.1
- 16 GB RAM
- VS Code v1.65.1
- (Also not using Nix)

( P.S. I'm super hyped that this is a VS code plugin, nice work!! )

**Comment by jwoudenberg** [comment]
Thank you @ryannhg!

It was a silly error in my new release process for the vscode extension, that caused some aspects of my Nix system to leak into the release bundle.

I just pushed a new version of the vscode plugin: 0.13.1. Does that one work for you?

**Comment by wolfadex** [comment]
It's working now. Thank you for the amazing tool!!
