### ISSUE TITLE
Elm-pair crashes on Linux: GLIBC_2.29 not found

### ISSUE THREAD

**Issue by Orasund** [jwoudenberg/elm-pair#17]
Hi, after installing Elm-pair on my linux computer i'm getting the following error:
```
Command failed: 
/home/orasund/.vscode/extensions/hjgames.elm-pair-0.13.1/elm-pair
/home/orasund/.vscode/extensions/hjgames.elm-pair-0.13.1/elm-pair: 
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found 
(required by /home/orasund/.vscode/extensions/hjgames.elm-pair-0.13.1/elm-pair)
```
Not sure how to fix this.

**Comment by jwoudenberg** [comment]
Hi @Orasund, thank you for reporting this! I'm going to look into this.

I have a theory about what's going on, and to test it it would be useful to know what Linux distribution and which version of that distribution you're running. Can you tell me? Thank you!

**Comment by Orasund** [comment]
Well i'm using a Chromebook (Chrome OS). I believe It's based on Debian.

Am Sa., 19. März 2022 um 08:50 Uhr schrieb Jasper Woudenberg <
***@***.***>:

**Comment by jwoudenberg** [comment]
Oh, super interesting! Thanks for letting me know!

**Comment by FabHof** [comment]
Maybe it helps: I have the same error message. Here is my (somewhat outdated) system:
`Linux tuxedo 5.4.0-104-generic #118~18.04.1-Ubuntu SMP Thu Mar 3 13:53:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jwoudenberg** [comment]
Thank you both, this is super useful info.

I think I have an idea how to address this. I'm going to take a look at it Monday!

**Comment by jwoudenberg** [comment]
Hi @Orasund and @FabHof. I just pushed release 14 which contains a fix for the issue. Would super appreciate it if you'd let me know if that works for you!

**Comment by FabHof** [comment]
It works for me now. Thank you for fixing it this fast.

**Comment by jwoudenberg** [comment]
Hooray! Thank you for letting me know!
