### ISSUE TITLE
Removing qualifier from custom type's constructors broken

### ISSUE THREAD

**Issue by stoeffel** [jwoudenberg/elm-pair#19]
I found an issue when renaming arguments of variants of a custom type.
![elm-pair-thingy](https://user-images.githubusercontent.com/1217681/161010607-ccb18d93-cb14-45f7-b39d-71e0b64906bf.gif)

Here the code to repro https://github.com/stoeffel/elm-pair-repro

**Comment by jwoudenberg** [comment]
That's a super clear demonstration. Thank you for reporting this, I'm going to look into it!

**Comment by jwoudenberg** [comment]
Sorry it took me a while to get to this, I wanted to finish cross-file renaming first. That's included in the next release (currently being published), along with a fix for this.
![output](https://user-images.githubusercontent.com/1525551/162158289-0ee744c8-8c08-4f54-bc89-eaef7c858ae0.gif)

**Comment by jwoudenberg** [comment]
Release 15 is live and contains a fix, so I'm going to close this issue. If you still run into issues please let me know. Thanks again for bringing this bug to my attention!
