### ISSUE TITLE
elm-pair clobbers cwd with `index.html`

### ISSUE THREAD

**Issue by Janiczek** [jwoudenberg/elm-pair#9]
I believe this is because `elm-pair` [doesn't specify](https://github.com/jwoudenberg/elm-pair/blob/d204cffdb2acd536bdc96a862817992c847f5b3d/elm-pair/src/elm/compiler.rs#L53-L56) `--output /dev/null` to `elm make`.

Tried on `release-6`.

### Steps to reproduce
1. ensure no `index.html` is present in your directory
2. open vim, open an Elm file, make some changes, close vim

Expected: ✅ still no `index.html`
Actual: :x: `index.html` is now present in your directory

https://user-images.githubusercontent.com/149425/152068132-cc7d80f0-ec76-4c45-a878-25dd94521f9d.mp4

**Comment by jwoudenberg** [comment]
Good find and solution! I fixed this on `main`, and will push out a new release that includes the fix later today. Many thanks!

**Comment by jwoudenberg** [comment]
I just pushed release 7 which includes a fix for this!
